FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["LogisticsApp.csproj", "."]
RUN dotnet restore "LogisticsApp.csproj"
COPY . .
RUN dotnet build "LogisticsApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LogisticsApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LogisticsApp.dll"]
